[dofbot]
min_servo1=0
max_servo1=180
min_servo2=0
max_servo2=180
min_servo3=0
max_servo3=180
min_servo4=0
max_servo4=180
min_servo5=0
max_servo5=180
min_servo6=0
max_servo6=180
dofbot_ip="127.0.0.1"
dofbot_port=6000
dofbot_app_connect_button_coodinate=[0, 0]
dofbot_check_network_coodinate=[0, 0]
dofbot_app_ip_input_coodinate=[0, 0]
dofbot_app_port_input_coodinate=[0, 0]
dofbot_app_connect_submit_button_coodinate=[0, 0]
dofbot_app_use_coodinate=[0, 0]
dofbot_app_servo1_scroll_coodinate=[0, 0]
dofbot_app_servo2_scroll_coodinate=[0, 0]
dofbot_app_servo3_scroll_coodinate=[0, 0]
dofbot_app_servo4_scroll_coodinate=[0, 0]
dofbot_app_servo5_scroll_coodinate=[0, 0]
dofbot_app_servo6_scroll_coodinate=[0, 0]